
/* Drop Tables */

DROP TABLE BOARD;
DROP TABLE BRANCHLOG;
DROP TABLE CUSTOMINFO;
DROP TABLE BRANCH;
DROP TABLE REBATE;
DROP TABLE PHONEMODEL;
DROP TABLE PHONEPRICE;



/* Drop Sequences */

DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE BRCLOG_SEQ;
DROP SEQUENCE BRC_SEQ;
DROP SEQUENCE CUSTOM_SEQ;
DROP SEQUENCE MODEL_SEQ;
DROP SEQUENCE PRICE_SEQ;
DROP SEQUENCE REBATE_SEQ;




/* Create Sequences */

CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE BRCLOG_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE BRC_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE CUSTOM_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE MODEL_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE PRICE_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;
CREATE SEQUENCE REBATE_SEQ INCREMENT BY 1 START WITH 1 NOCACHE;



/* Create Tables */

CREATE TABLE BOARD
(
	SEQ NUMBER NOT NULL,
	BOARD_CHK NUMBER(2) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	READCOUNT NUMBER DEFAULT 0,
	RP_SEQ NUMBER DEFAULT 0,
	WRITE_DATE DATE DEFAULT SYSDATE,
	WRITE_IP VARCHAR2(20),
	BRC_ID VARCHAR2(20) NOT NULL,
	FILENAME VARCHAR2(100),
	PRIMARY KEY (SEQ)
);

SELECT * FROM BRANCH;
CREATE TABLE BRANCH
(
	SEQ NUMBER NOT NULL UNIQUE,
	BRC_ID VARCHAR2(20) NOT NULL,
	ATTACH_ID VARCHAR2(20),
	PASSWORD VARCHAR2(20) NOT NULL,
	BRC_NAME VARCHAR2(30) NOT NULL,
	BRC_PHONE VARCHAR2(20),
	BRC_ADDR1 VARCHAR2(200),
	BRC_ADDR2 VARCHAR2(200),
	BRC_POST VARCHAR2(8),
	BRC_BOSS VARCHAR2(20) NOT NULL,
	BOSS_PHONE VARCHAR2(20),
	BRC_LEV NUMBER(2) DEFAULT 0,
	BRC_STATE NUMBER(2) DEFAULT 0,
	WRITE_ID VARCHAR2(20),
	WRITE_DATE DATE DEFAULT SYSDATE,
	WRITE_IP VARCHAR2(20),
	PRIMARY KEY (BRC_ID)
);


CREATE TABLE BRANCHLOG
(
	SEQ NUMBER NOT NULL,
	LOG_DATE DATE DEFAULT SYSDATE,
	LOG_IP VARCHAR2(20) NOT NULL,
	BRC_ID VARCHAR2(20) NOT NULL,
	PRIMARY KEY (SEQ)
);

SELECT * FROM CUSTOMINFO;
CREATE TABLE CUSTOMINFO
(
	SEQ NUMBER NOT NULL,
	CUST_NAME VARCHAR2(20),
	CUST_PHONE VARCHAR2(20),
	CONT_TERM VARCHAR2(20) NOT NULL,
	OPEN_DATE DATE NOT NULL,
	MEMO VARCHAR2(4000),
	WRITE_DATE DATE DEFAULT SYSDATE,
	WRITE_IP VARCHAR2(20),
	BRC_ID VARCHAR2(20) NOT NULL,
	PRICE_NAME VARCHAR2(50) NOT NULL,
	MODEL_CODE VARCHAR2(50) NOT NULL,
	REBATE number(8) NOT NULL,
	CUST_BIRTH DATE NOT NULL,
	PRIMARY KEY (SEQ)
);

SELECT * FROM PHONEMODEL;
CREATE TABLE PHONEMODEL
(
	SEQ NUMBER NOT NULL UNIQUE,
	MODEL_CODE VARCHAR2(50) NOT NULL,
	MODEL_NAME VARCHAR2(50) NOT NULL,
	FILENAME VARCHAR2(100) NOT NULL,
	OPEN_DATE DATE NOT NULL,
	WRITE_DATE DATE DEFAULT SYSDATE,
	WRITE_IP VARCHAR2(20),
	MAKE_COMP VARCHAR2(20) NOT NULL,
	PRIMARY KEY (MODEL_CODE)
);


CREATE TABLE PHONEPRICE
(
	SEQ NUMBER NOT NULL UNIQUE,
	PRICE_NAME VARCHAR2(50) NOT NULL,
	PRICE NUMBER(8) NOT NULL,
	USE_CALL VARCHAR2(100),
	USE_SMS VARCHAR2(100),
	USE_DATA VARCHAR2(100),
	MEMO VARCHAR2(500),
	WRITE_DATE DATE DEFAULT SYSDATE,
	WRITE_IP VARCHAR2(20),
	PRIMARY KEY (PRICE_NAME)
);


CREATE TABLE REBATE
(
	SEQ NUMBER NOT NULL,
	LTE34 NUMBER(8) DEFAULT 0,
	LTE42 NUMBER(8) DEFAULT 0,
	LTE52 NUMBER(8) DEFAULT 0,
	LTE62 NUMBER(8) DEFAULT 0,
	LTE72 NUMBER(8) DEFAULT 0,
	LTE100 NUMBER(8) DEFAULT 0,
	MODEL_CODE VARCHAR2(50) NOT NULL,
	PRIMARY KEY (SEQ)
);



/* Create Foreign Keys */

ALTER TABLE BOARD
	ADD FOREIGN KEY (BRC_ID)
	REFERENCES BRANCH (BRC_ID)
;


ALTER TABLE BRANCHLOG
	ADD FOREIGN KEY (BRC_ID)
	REFERENCES BRANCH (BRC_ID)
;


ALTER TABLE CUSTOMINFO
	ADD FOREIGN KEY (BRC_ID)
	REFERENCES BRANCH (BRC_ID)
;


ALTER TABLE CUSTOMINFO
	ADD FOREIGN KEY (MODEL_CODE)
	REFERENCES PHONEMODEL (MODEL_CODE)
;


ALTER TABLE REBATE
	ADD FOREIGN KEY (MODEL_CODE)
	REFERENCES PHONEMODEL (MODEL_CODE)
;


ALTER TABLE CUSTOMINFO
	ADD FOREIGN KEY (PRICE_NAME)
	REFERENCES PHONEPRICE (PRICE_NAME)
;

select * from rebate;



