SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE BOARD;
DROP TABLE BRANCHLOG;
DROP TABLE CUSTOMINFO;
DROP TABLE BRANCH;
DROP TABLE PHONEMODEL;
DROP TABLE PHONEPRICE;




/* Create Tables */

CREATE TABLE BOARD
(
	SEQ DECIMAL NOT NULL,
	BOARD_CHK DECIMAL(2) NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	CONTENT VARCHAR(4000) NOT NULL,
	READCOUNT DECIMAL DEFAULT 0,
	RP_SEQ DECIMAL DEFAULT 0,
	WRITE_DATE DATE DEFAULT NOW(), SYSDATE(),
	WRITE_IP VARCHAR(20),
	BRC_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (SEQ)
);


CREATE TABLE BRANCH
(
	SEQ DECIMAL NOT NULL UNIQUE,
	BRC_ID VARCHAR(20) NOT NULL,
	ATTACH_ID VARCHAR(20),
	PASSWORD VARCHAR(20) NOT NULL,
	BRC_NAME VARCHAR(30) NOT NULL,
	BRC_PHONE VARCHAR(12),
	BRC_ADDR1 VARCHAR(50),
	BRC_ADDR2 VARCHAR(50),
	BRC_POST VARCHAR(8),
	BRC_BOSS VARCHAR(20) NOT NULL,
	BOSS_PHONE VARCHAR(12),
	BRC_LEV DECIMAL(2) DEFAULT 0,
	BRC_STATE DECIMAL(2) DEFAULT 0,
	WRITE_ID VARCHAR(20),
	WRITE_DATE DATE DEFAULT NOW(), SYSDATE(),
	WRITE_IP VARCHAR(20),
	PRIMARY KEY (BRC_ID)
);


CREATE TABLE BRANCHLOG
(
	SEQ DECIMAL NOT NULL,
	LOG_DATE DATE DEFAULT NOW(), SYSDATE(),
	LOG_IP VARCHAR(20) NOT NULL,
	BRC_ID VARCHAR(20) NOT NULL,
	PRIMARY KEY (SEQ)
);


CREATE TABLE CUSTOMINFO
(
	SEQ DECIMAL NOT NULL,
	CUST_NAME VARCHAR(20),
	CUST_PHONE VARCHAR(20),
	CONT_TERM VARCHAR(20) NOT NULL,
	OPEN_DATE DATE NOT NULL,
	MEMO VARCHAR(4000),
	WRITE_DATE DATE DEFAULT NOW(), SYSDATE(),
	WRITE_IP VARCHAR(20),
	BRC_ID VARCHAR(20) NOT NULL,
	PRICE_NAME VARCHAR(50) NOT NULL,
	MODEL_CODE VARCHAR(50) NOT NULL,
	PRIMARY KEY (SEQ)
);


CREATE TABLE PHONEMODEL
(
	SEQ DECIMAL NOT NULL UNIQUE,
	MODEL_CODE VARCHAR(50) NOT NULL,
	MODEL_NAME VARCHAR(50) NOT NULL,
	FILENAME VARCHAR(100) NOT NULL,
	OPEN_DATE DATE NOT NULL,
	WRITE_DATE DATE DEFAULT NOW(), SYSDATE(),
	WRITE_IP VARCHAR(20),
	PRIMARY KEY (MODEL_CODE)
);


CREATE TABLE PHONEPRICE
(
	SEQ DECIMAL NOT NULL UNIQUE,
	PRICE_NAME VARCHAR(50) NOT NULL,
	PRICE DECIMAL(8) NOT NULL,
	USE_CALL VARCHAR(100),
	USE_SMS VARCHAR(100),
	USE_DATA VARCHAR(100),
	MEMO VARCHAR(500),
	WRITE_DATE DATE DEFAULT NOW(), SYSDATE(),
	WRITE_IP VARCHAR(20),
	PRIMARY KEY (PRICE_NAME)
);



/* Create Foreign Keys */

ALTER TABLE BOARD
	ADD FOREIGN KEY (BRC_ID)
	REFERENCES BRANCH (BRC_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BRANCHLOG
	ADD FOREIGN KEY (BRC_ID)
	REFERENCES BRANCH (BRC_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CUSTOMINFO
	ADD FOREIGN KEY (BRC_ID)
	REFERENCES BRANCH (BRC_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CUSTOMINFO
	ADD FOREIGN KEY (MODEL_CODE)
	REFERENCES PHONEMODEL (MODEL_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CUSTOMINFO
	ADD FOREIGN KEY (PRICE_NAME)
	REFERENCES PHONEPRICE (PRICE_NAME)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



