SELECT B.* 
FROM (SELECT A.*, rownum AS rnum
	  FROM (SELECT cust_name, CUST_PHONE, CONT_TERM, OPEN_DATE, MEMO,
				   WRITE_DATE, WRITE_IP, BRC_ID, PRICE_NAME, MODEL_CODE, REBATE, to_char(CUST_BIRTH, 'YYYY-DD-MM') AS CUST_BIRTH 
	  			   FROM CUSTOMINFO) A) B
WHERE 11 <= rnum AND rnum <= 20
ORDER BY rnum ASC;

DELETE FROM CUSTOMINFO
WHERE seq = 362;

SELECT * FROM CUSTOMINFO;

SELECT * FROM BRANCH;
SELECT B.* 
	FROM (SELECT A.*, rownum AS rnum
	  FROM (SELECT brc_id
	  		FROM BRANCH) A) B
ORDER BY rnum ASC;